<?php

function zendesk_connect_theme($existing, $type, $theme, $path) {
  return array(
    'requests' => array(
      'variables' => array(
        'requests' => NULL,
      ),
    ),
    'request' => array(
      'variables' => array(
        'request_id' => NULL,
        'request' => NULL,
        'comments' => NULL,
        'commentAuthors' => NULL,
        'form' => NULL,
      ),
    ),
  );
}

function zendesk_connect_user_insert(\Drupal\user\Entity\User $user) {
  $config = \Drupal::service('zendesk_connect.settings');
  $client = \Drupal::service('zendesk_connect.client_factory')->get($config->get('basic.email'));

  $postData = [
    'name' => $user->getEmail(),
    'email' => $user->getEmail(),
    "verified" => TRUE,
  ];

  try {
    $client->users()->create($postData);
  } catch(Exception $e) {
    \Drupal::logger('zendesk_connect')->notice('Caught exception: ' . $e->getMessage() . "\n");
  }
}
