<?php

function zendesk_connect_theme($existing, $type, $theme, $path) {
  return array(
    'requests' => array(
      'variables' => array(
        'requests' => NULL,
      ),
    ),
    'request' => array(
      'variables' => array(
        'request_id' => NULL,
        'request' => NULL,
        'comments' => NULL,
        'commentAuthors' => NULL,
        'form' => NULL,
      ),
    ),
  );
}
